name: venv
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python
  - pytorch 
  - pytorch-cuda=12.1
  - fenics-dolfinx
  - numpy
  - pandas
  - matplotlib
  - scipy
  - shapely
  - pytest